# this is a simple script to find mismatch between the moves generated by our engine and the moves generated by the stockfish engine

user_moves = {
    "d5d6": 79549,
    "d5e6": 97429,
    "a2a3": 94405,
    "a2a4": 90978,
    "b2b3": 81066,
    "g2g3": 77468,
    "g2g4": 75677,
    "g2h3": 82759,
    "e5f7": 88799,
    "e5d7": 93913,
    "e5g6": 83866,
    "e5g4": 79912,
    "e5d3": 77431,
    "e5c6": 83885,
    "e5c4": 77752,
    "c3b5": 81498,
    "c3d1": 84782,
    "c3b1": 84773,
    "c3a4": 91447,
    "d2e3": 90274,
    "d2f4": 84869,
    "d2g5": 87951,
    "d2h6": 82323,
    "d2c1": 83037,
    "e2d3": 85119,
    "e2c4": 84835,
    "e2b5": 79739,
    "e2a6": 69334,
    "e2f1": 88728,
    "e2d1": 74963,
    "a1b1": 83348,
    "a1c1": 83263,
    "a1d1": 79695,
    "h1g1": 84876,
    "h1f1": 81563,
    "f3g4": 92037,
    "f3h5": 95034,
    "f3f4": 90488,
    "f3f5": 104992,
    "f3f6": 77838,
    "f3g3": 94461,
    "f3h3": 98524,
    "f3e3": 92505,
    "f3d3": 83727,
    "e1f1": 77887,
    "e1d1": 79989,
    "e1c1": 79803,
    "e1g1": 86975,
}

stockfish_moves = {
    "a2a3": 94405,
    "b2b3": 81066,
    "g2g3": 77468,
    "d5d6": 79551,
    "a2a4": 90978,
    "g2g4": 75677,
    "g2h3": 82759,
    "d5e6": 97464,
    "c3b1": 84773,
    "c3d1": 84782,
    "c3a4": 91447,
    "c3b5": 81498,
    "e5d3": 77431,
    "e5c4": 77752,
    "e5g4": 79912,
    "e5c6": 83885,
    "e5g6": 83866,
    "e5d7": 93913,
    "e5f7": 88799,
    "d2c1": 83037,
    "d2e3": 90274,
    "d2f4": 84869,
    "d2g5": 87951,
    "d2h6": 82323,
    "e2d1": 74963,
    "e2f1": 88728,
    "e2d3": 85119,
    "e2c4": 84835,
    "e2b5": 79739,
    "e2a6": 69334,
    "a1b1": 83348,
    "a1c1": 83263,
    "a1d1": 79695,
    "h1f1": 81563,
    "h1g1": 84876,
    "f3d3": 83727,
    "f3e3": 92505,
    "f3g3": 94461,
    "f3h3": 98524,
    "f3f4": 90488,
    "f3g4": 92037,
    "f3f5": 104992,
    "f3h5": 95034,
    "f3f6": 77838,
    "e1d1": 79989,
    "e1f1": 77887,
    "e1g1": 86975,
    "e1c1": 79803,
}

def find_mismatch(user_moves, stockfish_moves):
    mismatch = []
    for move in user_moves:
        if move not in stockfish_moves:
            mismatch.append(move)
        elif user_moves[move] != stockfish_moves[move]:
            mismatch.append(move)
    return mismatch

def generate_mismatch_report(mismatch):
    print("Mismatch found in the following moves:")
    for move in mismatch:
        print(f"Move: {move}")
        print(f"User move count: {user_moves[move]}")
        print(f"Stockfish move count: {stockfish_moves[move]}")
        print(f"difference: {stockfish_moves[move] - user_moves[move]}")
        print()
        
mismatch = find_mismatch(user_moves, stockfish_moves)
generate_mismatch_report(mismatch)

