# this is a simple script to find mismatch between the moves generated by our engine and the moves generated by the stockfish engine

user_moves = {
    "c7c6": 48,
    "c7c5": 48,
    "d7d6": 46,
    "e6d5": 47,
    "g6g5": 46,
    "b4c3": 44,
    "b4a3": 47,
    "g2g1": 3,
    "g2g1": 3,
    "g2g1": 47,
    "g2g1": 47,
    "g2h1": 3,
    "g2h1": 3,
    "g2h1": 47,
    "g2h1": 47,
    "b6c8": 47,
    "b6d5": 47,
    "b6c4": 46,
    "b6a4": 47,
    "f6g8": 48,
    "f6h7": 48,
    "f6h5": 48,
    "f6g4": 47,
    "f6e4": 50,
    "f6d5": 48,
    "g7f8": 47,
    "g7h6": 47,
    "a6b7": 47,
    "a6c8": 47,
    "a6b5": 46,
    "a6c4": 46,
    "a6d3": 45,
    "a6e2": 42,
    "a8b8": 47,
    "a8c8": 47,
    "a8d8": 47,
    "h8h7": 47,
    "h8h6": 47,
    "h8h5": 47,
    "h8h4": 46,
    "h8h3": 45,
    "h8h2": 46,
    "h8g8": 47,
    "h8f8": 47,
    "e7f8": 47,
    "e7d8": 47,
    "e7d6": 46,
    "e7c5": 47,
    "e8f8": 47,
    "e8d8": 47,
    "e8c8": 47,
    "e8g8": 47,
}

stockfish_moves = {}
with open("stockfish.txt", "r") as file:
    for line in file:
        if ":" in line:
            move, count = line.strip().split(": ")
            stockfish_moves[move] = int(count)


def find_mismatch(user_moves, stockfish_moves):
    mismatch = []
    for move in stockfish_moves:
        try:
            if stockfish_moves[move] != user_moves[move]:
                mismatch.append(move)
        except KeyError:
            mismatch.append(move)

    return mismatch


def generate_mismatch_report(mismatch):
    print(f"Total mismatch found: {len(mismatch)}")
    print("Mismatch found in the following moves:")
    for move in mismatch:
        try:
            print(f"Move: {move}")
            print(f"User move count: {user_moves[move]}")
            print(f"Stockfish move count: {stockfish_moves[move]}")
            print(f"difference: {stockfish_moves[move] - user_moves[move]}")
            print()
        except KeyError:
            print(f"User move count: 0 (Move not found)")
            print(f"Stockfish move count: {stockfish_moves[move]}")
            print(f"difference: {stockfish_moves[move]}")
            print()


mismatch = find_mismatch(user_moves, stockfish_moves)
generate_mismatch_report(mismatch)
